version: '3.8'

services:
  contenedor-alfa:
    image: nginx:alpine
    container_name: desarrollo
    ports:
      - "8081:80"
    volumes:
      # Usamos ./ seguido del nombre exacto de la carpeta que subiste a GitHub
      - ./Desarrollo:/usr/share/nginx/html:ro

  contenedor-beta:
    image: nginx:alpine
    container_name: produccion
    ports:
      - "8082:80"
    volumes:
      - ./Produccion:/usr/share/nginx/html:ro
