version: '3.8'

services:
  contenedor-alfa:
    image: nginx:alpine
    container_name: web-render-1
    ports:
      - "8081:80"
    volumes:
      - ./web1:/usr/share/nginx/html

  contenedor-beta:
    image: nginx:alpine
    container_name: web-render-2
    ports:
      - "8082:80"
    volumes:
      - ./web2:/usr/share/nginx/html
